<?php

/**
 * @package Skeleton module
 * @author Iurii Makukh <gplcart.software@gmail.com>
 * @copyright Copyright (c) 2015, Iurii Makukh
 * @license https://www.gnu.org/licenses/gpl.html GNU/GPLv3
 */
return array(
    'alias' => /* @text */'URL aliases',
    'bookmark' => /* @text */'Bookmarks',
    'help' => /* @text */'Help',
    'construct' => /* @text */'Class construction',
    'destruct' => /* @text */'Class destruction',
    'cli' => /* @text */'Command line',
    'template' => /* @text */'Templates',
    'theme' => /* @text */'Theme',
    'library' => /* @text */'Libraries',
    'route' => /* @text */'URL routing',
    'cron' => /* @text */'CRON',
    'address' => /* @text */'User addresses',
    'backup' => /* @text */'Backup',
    'cache' => /* @text */'Cache',
    'cart' => /* @text */'Shopping cart',
    'category' => /* @text */'Categories',
    'city' => /* @text */'Cities',
    'collection' => /* @text */'Collections',
    'condition' => /* @text */'Trigger conditions',
    'country' => /* @text */'Countries',
    'currency' => /* @text */'Currencies',
    'dashboard' => /* @text */'Dashboard',
    'field' => /* @text */'Product fields',
    'file' => /* @text */'Files',
    'filter' => /* @text */'Filters',
    'imagestyle' => /* @text */'Images',
    'install' => /* @text */'Installation',
    'job' => /* @text */'Bulk jobs',
    'language' => /* @text */'Localization',
    'mail' => /* @text */'E-mail',
    'order' => /* @text */'Orders',
    'page' => /* @text */'Pages',
    'payment' => /* @text */'Payment methods',
    'price' => /* @text */'Prices',
    'product' => /* @text */'Products',
    'rating' => /* @text */'Ratings',
    'report' => /* @text */'Reporting',
    'review' => /* @text */'Reviews',
    'search' => /* @text */'Searching',
    'shipping' => /* @text */'Shipping methods',
    'sku' => /* @text */'SKU',
    'state' => /* @text */'Country states',
    'store' => /* @text */'Stores',
    'transaction' => /* @text */'Payment transactions',
    'trigger' => /* @text */'Triggers',
    'user' => /* @text */'Users',
    'validator' => /* @text */'Validating',
    'wishlist' => /* @text */'Wishlists',
    'zone' => /* @text */'Geo zones',
    'module' => /* @text */'Modules',
    'oauth' => /* @text */'Oauth'
);
